name: Deploy Backend
 
on:
  push:

jobs:
  deploy-be:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     tags: hieudan/ume:latest
      #     file: ./dockers/client.Dockerfile
      #     context: .

      - name: ssh key passphrase
        uses: appleboy/ssh-action@master
        with:
          continue-on-error: true
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          port: ${{ secrets.AWS_PORT }}
          script: |-
            sudo docker pull hieudan/ume
            sudo docker stop backend_server
            sudo docker rm backend_server
            sudo docker run --detach --name backend_server -p 3000:3000 hieudan/ume
#            sudo docker rmi  $(sudo docker images -aq)
 