name: Build Ume-Client

on:
  workflow_dispatch:
    inputs:
      servicePath:
        description: "Path of service"
        required: false
  registry_package:
    types: [published]
  push:
    paths:
      - "apps/client/**"
      - "github/workflows/build-client.yaml"
    branches:
      - "master"

env:
  DOCKER_SERVER: ${{ secrets.DOCKER_SERVER }}
jobs:
  docker:
    name: Build Portal
    runs-on: [ 'self-hosted' ]
    steps:
      - uses: actions/checkout@v3
      - run: git pull

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_SERVER }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker get tag release
        id: docker_tag_release
        run: echo "docker_tag_release=$(make get-portal-image-tag)" >> $GITHUB_ENV
        working-directory: "./"

      - name: Docker cache image
        id: cache_image
        run: echo "cache_image=$(make get-tag-cache-portal-image)" >> $GITHUB_ENV
        working-directory: "./"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockers/portal.Dockerfile
          push: true
          tags: ${{ env.docker_tag_release }}
#           cache-from: type=registry,ref=${{ env.cache_image }}
#           cache-to: type=registry,ref=${{ env.cache_image }}

      - name: Get tag release
        id: tag_release
        run: echo "tag_release=$(make get-portal-tag-release)" >> $GITHUB_ENV
        working-directory: "./"
      - name: Mark tag release
        uses: EndBug/latest-tag@latest
        with:
          tag-name: ${{ env.tag_release }}
          description: "release: Ume - Client"
      
