name: Build Ume-Client

on:
  workflow_dispatch:
    inputs:
      servicePath:
        description: "Path of service"
        required: false
  registry_package:
    types: [published]
  push:
    paths:
      - "app/client/**"
      - "github/workflows/build-client.yaml"
    branches:
      - "master"
    
      